"""empty message

Revision ID: 06876b37a7a5
Revises: 7b0cb61c1b48
Create Date: 2018-06-06 18:32:15.025513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06876b37a7a5'
down_revision = '7b0cb61c1b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_symbol', table_name='player')
    op.drop_column('player', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('symbol', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_player_symbol', 'player', ['symbol'], unique=False)
    # ### end Alembic commands ###
