"""empty message

Revision ID: 5152c18213dc
Revises: a5ac4a44a806
Create Date: 2018-06-04 11:46:07.730999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5152c18213dc'
down_revision = 'a5ac4a44a806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_symbol', table_name='player')
    op.create_index(op.f('ix_player_symbol'), 'player', ['symbol'], unique=False)
    op.drop_index('ix_player_username', table_name='player')
    op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_username'), table_name='player')
    op.create_index('ix_player_username', 'player', ['username'], unique=True)
    op.drop_index(op.f('ix_player_symbol'), table_name='player')
    op.create_index('ix_player_symbol', 'player', ['symbol'], unique=True)
    # ### end Alembic commands ###
