"""empty message

Revision ID: 7b0cb61c1b48
Revises: b76434967559
Create Date: 2018-06-06 18:21:50.997029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0cb61c1b48'
down_revision = 'b76434967559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('symbol', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_player_symbol'), 'player', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_symbol'), table_name='player')
    op.drop_column('player', 'symbol')
    # ### end Alembic commands ###
