"""empty message

Revision ID: 8d13cbb1147c
Revises: 82996a5f9b30
Create Date: 2018-05-25 16:11:55.268190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d13cbb1147c'
down_revision = '82996a5f9b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'active')
    # ### end Alembic commands ###
