"""empty message

Revision ID: a5ac4a44a806
Revises: 8d13cbb1147c
Create Date: 2018-05-30 12:22:01.087806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ac4a44a806'
down_revision = '8d13cbb1147c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'game_id')
    # ### end Alembic commands ###
