"""empty message

Revision ID: b76434967559
Revises: 5152c18213dc
Create Date: 2018-06-04 21:30:41.530242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b76434967559'
down_revision = '5152c18213dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_symbol', table_name='player')
    op.drop_column('player', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('symbol', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_player_symbol', 'player', ['symbol'], unique=False)
    # ### end Alembic commands ###
